### ISSUE TITLE
Add tests for SPI added for JAF 2.1

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jaf-tck#31]

**Comment by gurunrao** [comment]
@lukasj - Please add more details to for issue.

**Comment by jbescos** [comment]
PR was merged, can we close this?

**Comment by lukasj** [comment]
the best is to use [closing words](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to not forget...
