### ISSUE TITLE
TCK for activation doesn't pass anymore on GF

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jaf-tck#46]
Every test now fails with something like:

```
[javatest.batch] command: com.sun.javatest.lib.ExecStdTestOtherJVMCmd CLASSPATH=/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/tests/../classes:/home/jenkins/agent/workspace/jaf-tck_master/JTwork/activation-tck/classes:/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/javatest.jar:/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/sigtest.jar:/home/jenkins/agent/workspace/jaf-tck_master/jakarta.activation.jar:/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/classes HOME=/ /opt/jdk-11.0.10/bin/java -verify javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test
[javatest.batch] java.lang.NoClassDefFoundError: jakarta/activation/ActivationDataFlavor
[javatest.batch] 	at javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test.callADF_1(ActivationDataFlavor_Test.java:61)
[javatest.batch] 	at javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test.testForActivationDF1(ActivationDataFlavor_Test.java:44)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[javatest.batch] 	at com.sun.javatest.lib.TestCases.invokeTestCases(TestCases.java:195)
[javatest.batch] 	at com.sun.javatest.lib.MultiTest.run(MultiTest.java:134)
[javatest.batch] 	at javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test.main(ActivationDataFlavor_Test.java:37)
[javatest.batch] Caused by: java.lang.ClassNotFoundException: jakarta.activation.ActivationDataFlavor
[javatest.batch] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
[javatest.batch] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
[javatest.batch] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[javatest.batch] 	... 9 more
```

See: https://ci.eclipse.org/jakartaee-tck/job/jaf-tck/job/master/47/consoleFull

@gurunrao any idea what could be causing this?

(x-posting to https://github.com/eclipse-ee4j/angus-activation/issues/6 as well)

**Comment by gurunrao** [comment]
> Every test now fails with something like:
> 
> ```
> [javatest.batch] command: com.sun.javatest.lib.ExecStdTestOtherJVMCmd CLASSPATH=/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/tests/../classes:/home/jenkins/agent/workspace/jaf-tck_master/JTwork/activation-tck/classes:/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/javatest.jar:/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/sigtest.jar:/home/jenkins/agent/workspace/jaf-tck_master/jakarta.activation.jar:/home/jenkins/agent/workspace/jaf-tck_master/activation-tck/classes HOME=/ /opt/jdk-11.0.10/bin/java -verify javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test
> [javatest.batch] java.lang.NoClassDefFoundError: jakarta/activation/ActivationDataFlavor
> [javatest.batch] 	at javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test.callADF_1(ActivationDataFlavor_Test.java:61)
> [javatest.batch] 	at javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test.testForActivationDF1(ActivationDataFlavor_Test.java:44)
> [javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [javatest.batch] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [javatest.batch] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> [javatest.batch] 	at com.sun.javatest.lib.TestCases.invokeTestCases(TestCases.java:195)
> [javatest.batch] 	at com.sun.javatest.lib.MultiTest.run(MultiTest.java:134)
> [javatest.batch] 	at javasoft.sqe.tests.api.jakarta.activation.ActivationDataFlavor.ActivationDataFlavor_Test.main(ActivationDataFlavor_Test.java:37)
> [javatest.batch] Caused by: java.lang.ClassNotFoundException: jakarta.activation.ActivationDataFlavor
> [javatest.batch] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
> [javatest.batch] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
> [javatest.batch] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
> [javatest.batch] 	... 9 more
> ```
> 
> See: https://ci.eclipse.org/jakartaee-tck/job/jaf-tck/job/master/47/consoleFull
> 
> @gurunrao any idea what could be causing this?
> 
> (x-posting to [eclipse-ee4j/angus-activation#6](https://github.com/eclipse-ee4j/angus-activation/issues/6) as well)

Test results are passing - https://ci.eclipse.org/jakartaee-tck/job/jaf-tck/job/master/49/testReport/
CI Job[https://ci.eclipse.org/jakartaee-tck/job/jaf-tck/] has been refreshed [to pick changes from latest JenkinsFile].

**Comment by arjantijms** [comment]
@gurunrao, I wonder, the jaf-tck only references a master, which seemingly has been changed over to Jakarta EE 10. How can we still do certifications for Jakarta EE 9.1?

Even more confusing, does the JAF-TCK job ever tests GlassFish? I looked at the logs and I see it's downloading:

```
ACTIVATION_BUNDLE_URL=https://jakarta.oss.sonatype.org/content/repositories/staging/com/sun/activation/jakarta.activation/2.0.0/jakarta.activation-2.0.0.jar

ANGUS_BUNDLE_URL=https://jakarta.oss.sonatype.org/content/repositories/staging/org/eclipse/angus/angus-activation/1.0.0-SNAPSHOT/angus-activation-1.0.0-20210811.141336-3.jar
```

Should it not take the jars from the /modules folder in GlassFish?

Maybe I'm missing something here.

**Comment by arjantijms** [comment]
In the latest run 49 I see:

```
+ wget --progress=bar:force --no-cache https://jakarta.oss.sonatype.org/content/repositories/staging/jakarta/activation/jakarta.activation-api/2.1.0/jakarta.activation-api-2.1.0.jar -O /home/jenkins/agent/workspace/jaf-tck_master/jakarta.activation-api.jar
```

and

```
+ wget --progress=bar:force --no-cache https://jakarta.oss.sonatype.org/content/repositories/staging/org/eclipse/angus/angus-activation/1.0.0-SNAPSHOT/angus-activation-1.0.0-20210811.141336-3.jar -O /home/jenkins/agent/workspace/jaf-tck_master/angus-activation.jar
```

**Comment by arjantijms** [comment]
@lukasj said:

```
What I think that job should do is:

* grab appropriate version of the TCK and unzip
* grab glassfish and unzip
* update paths in TCK's ts.jte to point to the right jars from the unzipped server (what if GF uses ie awsomeGFact.jar * instead of current jakarta.activation.jar?)
* run the TCK
```

That looks more logical, but I think that's not what's happening. What the job seems to do is:

```
* Run JenkinsFile from master of jaf-tck github repo
* Download jars from the staging repo
* update paths in TCK's ts.jte to point to the jars just downloaded
* run the TCK
```

Am I missing something still?

**Comment by gurunrao** [comment]
PR https://github.com/eclipse-ee4j/jaf-tck/pull/47 has been raised for update of Job configuration and run scripts.
Once GF is integrated with activation 2.1, will be able to complete PR test and move same from 'Draft' to 'Ready to Review'.

**Comment by gurunrao** [comment]
PR #47 has been merged.
