### ISSUE TITLE
Challenge for the Activation 2.1 TCK which needs to work with EE implementations that are not JPMS based

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jaf-tck#55]
I downloaded https://download.eclipse.org/jakartaee/activation/2.1/jakarta-activation-tck-2.1.0.zip, extracted contents and tried:
1.  export JARPATH=wildfly/ee-9/dist/target/wildfly-preview-27.0.0.Alpha2-SNAPSHOT/modules/system/layers/base/org/eclipse/angus/activation/main/angus-activation-1.0.0.jar
2. export TS_HOME=$PWD
3. I updated the lib/ts.jte to have the same values for ^
4. ant run

I get the below failure:

> [javatest.batch] Error occurred during initialization of boot layer
> [javatest.batch] java.lang.module.FindException: Module jakarta.activation not found
> [javatest.batch] Java Result: 1
> 

I tried the above steps following the TCK installation steps:
```
4.2 Configuring Your Environment to Run the TCK
Against the Vendor Implementation
After configuring your environment as described in this section, continue with the instructions in
Section 4.4, "Using the JavaTest Harness Software."
In these instructions, variables in angle brackets need to be expanded for each
platform. For example, <TS_HOME> becomes $TS_HOME on Solaris/Linux and %TS_HOME% on
Windows. In addition, the forward slashes (/) used in all of the examples need to be
replaced with backslashes (\) for Windows. Finally, be sure to use the appropriate

separator for your operating system when specifying multiple path entries (; on
Windows, : on UNIX/Linux).
On Windows, you must escape any backslashes with an extra backslash in path
separators used in any of the following properties, or use forward slashes as a path
separator instead.
1. Set the following environment variables in your shell environment:
1. JAVA_HOME to the directory in which Java SE 11+ is installed
2. TS_HOME to the directory in which the Activation TCK 2.1 software is installed
3. JARPATH to the directory in which the Activation 2.1 Vendor Implementation has been installed
4. PATH to include the following directories: JAVA_HOME/bin and ANT_HOME/bin
2. Edit your <TS_HOME>/lib/ts.jte file and set the following environment variables:
1. Set the JAVA_HOME property to the directory in which Java SE 11+ is installed.
2. Set the TS_HOME property to the directory in which the Activation TCK 2.1 software is installed.
3. Set the JARPATH property to the directory in which the Activation 2.1 Vendor Implementation has
been installed.
```

I also tried copying the https://ci.eclipse.org/jakartaee-tck/job/jaf-tck/job/master/79/console job setup by setting the JARPATH to the root folder that contains other folders that have various jars that includes Activation:
```
export JARPATH=wildfly-preview-27.0.0.Alpha2-SNAPSHOT/modules/system/layers/base
```

^ gives the same failure.

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/jaf-tck/blob/master/docker/run_activationtck.sh (contained in the TCK ZIP) seems to be for GlassFish only.  

I will try the instructions in https://github.com/eclipse-ee4j/jaf-tck/blob/master/QuickStart.txt next (still hoping its an operator error).

**Comment by lukasj** [comment]
Vars need to point to jars, not directories, I believe

**Comment by scottmarlow** [comment]
I updated my local environment to point to jars via JARPATH (matches the lib/ts.jte settings):

> export JARPATH=wildfly-preview-27.0.0.Alpha2-SNAPSHOT/modules/system/layers/base/org/eclipse/angus/activation/main/angus-activation-1.0.0.jar:wildfly-preview-27.0.0.Alpha2-SNAPSHOT/modules/system/layers/base/jakarta/activation/api/main/jakarta.activation-api-2.1.0.jar
> 
> ant run
> Buildfile: /tmp/jaf/activation-tck/build.xml
> 
> run:
> [javatest.batch] Error occurred during initialization of boot layer
> [javatest.batch] java.lang.module.FindException: Module jakarta.activation not found
> [javatest.batch] Java Result: 1

**Comment by scottmarlow** [comment]
> Vars need to point to jars, not directories, I believe

https://github.com/eclipse-ee4j/jaf-tck/blob/master/docker/run_activationtck.sh#L76 contains the following that appears to add  the glassfish modules folder to JARPATH:
```
if [[ "$RUNTIME" == "Glassfish" ]]; then
  sed -i "s#^JARPATH=.*#JARPATH=$WORKSPACE/$TOP_GLASSFISH_DIR/glassfish/modules#g" ${TS_HOME}/lib/ts.jte
  sed -i "s#^JARPATH=.*#JARPATH=$WORKSPACE/$TOP_GLASSFISH_DIR/glassfish/modules#g" ${TS_HOME}/lib/ts.pluggability.jte

else 
  sed -i "s#^JARPATH=.*#JARPATH=$WORKSPACE#g" ${TS_HOME}/lib/ts.jte
  sed -i "s#^JARPATH=.*#JARPATH=$WORKSPACE#g" ${TS_HOME}/lib/ts.pluggability.jte
fi
```

**Comment by scottmarlow** [comment]
The part that I am not seeing is where the Activation TCK test configures the (Java SE style) classpath settings.

**Comment by lukasj** [comment]
I'm not that smart to do complicated stuff. Did you tried to follow comments and variables in the `ts.jte` file?

```
ljungman-mac:activation-tck lukas$ diff -u lib/ts.jte lib/ts.jte.orig
--- lib/ts.jte	2022-06-27 21:55:16.000000000 +0200
+++ lib/ts.jte.orig	2022-06-27 21:49:31.000000000 +0200
@@ -34,13 +34,13 @@
 
 # And this style naming convention for UNIX.
 # TS_HOME=/home/abc/jaftck
-TS_HOME=/Users/lukas/tmp/act/activation-tck/
+TS_HOME=/home/jenkins/agent/workspace/jaf-tck_master
 
 # Set this to the installation of your JDK.
 
 ##JAVA_HOME=D:\\jdk-11
 ##JAVA_HOME=/usr/jdk-11
-JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home
+JAVA_HOME=/opt/jdk-11.0.10
 
 # Set this to the directory containing the Activation .jar 
 # file (i.e., jakarta.activation-api.jar)
@@ -50,11 +50,11 @@
 
 # Set the path to the jakarta.activation-api.jar
 #API_JAR=${JARPATH}\\jakarta.activation-api.jar
-API_JAR=/Users/lukas/java/wildfly-preview-27.0.0.Alpha1/modules/system/layers/base/jakarta/activation/api/main/jakarta.activation-api-2.1.0.jar
+API_JAR=${JARPATH}/jakarta.activation-api.jar
 
 # Set the Activation implementation path 
 ##CI_JAR=$JARPATH\\angus-activation.jar
-CI_JAR=/Users/lukas/java/wildfly-preview-27.0.0.Alpha1/modules/system/layers/base/org/eclipse/angus/activation/main/angus-activation-1.0.0.jar
+CI_JAR=$JARPATH/angus-activation.jar
 
 ##TESTCLASS=$TS_HOME\\classes
 TESTCLASS=$TS_HOME/classes
ljungman-mac:activation-tck lukas$
```

and:
```
ljungman-mac:activation-tck lukas$ ant run
...
[javatest.batch] ***************************************************************
[javatest.batch] Completed running 91 tests.
[javatest.batch] Number of Tests Passed      = 91
[javatest.batch] Number of Tests Failed      = 0
[javatest.batch] Number of Tests with Errors = 0
[javatest.batch] Number of Tests Not Run     = 0
[javatest.batch] ---------------------------------------------------------------
...
BUILD SUCCESSFUL
Total time: 33 seconds
```

**Comment by scottmarlow** [comment]
> Did you try to follow comments and variables in the `ts.jte` file?

I'm checking this out now, thanks for the suggestion!

**Comment by lukasj** [comment]
FYI: API_JAR value is passed to module-path, CI_JAR is passed to classpath. Given that the API must define module name in EE10 and the module name must be `jakarta.activation`, following alternatives are possible too:

* single jar (former jakarta.activation.jar):
```
API_JAR=${path.to}/jakarta.activation.jar
CI_JAR=empty
```
* API + CI on module path:
```
API_JAR=${path.to}/jakarta.activation-api.jar:${path.to}angus-activation-1.0.0.jar
CI_JAR=empty
```

everything else will fail (...as expected)
