### ISSUE TITLE
release JAF TCK for Jakarta EE 9

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jaf-tck#8]
Release of standalone JAF TCK is needed for Jakarta EE 9.  Will need to include documentation on how EE implementations can run it.  

Looks like https://ci.eclipse.org/jaf is setup to build/run the JAF TCK.  I think that we will also need a CI release job, could someone create that.  Perhaps a TCK snapshot release CI job would be helpful as well.

**Comment by alwin-joseph** [comment]
For the record :

https://ci.eclipse.org/mail/job/eftl-mailtck-build-run is created to update the bundle directly at https://download.eclipse.org/ee4j/jaf/tck/eftl/

**Comment by lukasj** [comment]
I believe this has been done already
